import { create } from 'zustand'
import { persist } from 'zustand/middleware'

const fontOptions = [
  { id: 'inter', label: 'Inter', css: "'Inter', sans-serif" },
  { id: 'jakarta', label: 'Plus Jakarta Sans', css: "'Plus Jakarta Sans', sans-serif" },
  { id: 'manrope', label: 'Manrope', css: "'Manrope', sans-serif" },
  { id: 'space-grotesk', label: 'Space Grotesk', css: "'Space Grotesk', sans-serif" },
]

const themeOptions = [
  {
    id: 'light',
    label: 'Light',
    vars: {
      '--bg-color': '#ffffff',
      '--surface-color': '#ffffff',
      '--surface-muted': '#f8fafc',
      '--text-color': '#0f172a',
      '--muted-color': '#475569',
      '--primary-color': '#3b82f6',
      '--secondary-color': '#334155',
      '--accent-color': '#f1f5f9',
      '--border-color': '#cbd5e1',
      '--danger-color': '#ef4444',
      '--danger-contrast-color': '#ffffff',
      '--overlay-color': 'rgba(15, 23, 42, 0.45)',
      '--shadow-color': '15, 23, 42',
      '--skeleton-base': '#e5e7eb',
      '--skeleton-highlight': '#f3f4f6',
      '--control-bg': '#ffffff',
      '--control-text': '#0f172a',
      '--control-border': '#94a3b8',
      '--control-focus': '#3b82f6',
      '--control-focus-ring': 'rgba(59, 130, 246, 0.2)',
    },
  },
  {
    id: 'dark',
    label: 'Dark',
    vars: {
      '--bg-color': '#0b1220',
      '--surface-color': '#1e293b',
      '--surface-muted': '#1e293b',
      '--text-color': '#ffffff',
      '--muted-color': '#e2e8f0',
      '--primary-color': '#60a5fa',
      '--secondary-color': '#f1f5f9',
      '--accent-color': '#1e293b',
      '--border-color': '#ffffff',
      '--danger-color': '#f87171',
      '--danger-contrast-color': '#0b1220',
      '--overlay-color': 'rgba(2, 6, 23, 0.65)',
      '--shadow-color': '2, 6, 23',
      '--skeleton-base': '#334155',
      '--skeleton-highlight': '#475569',
      '--control-bg': '#1e293b',
      '--control-text': '#ffffff',
      '--control-border': '#ffffff',
      '--control-focus': '#60a5fa',
      '--control-focus-ring': 'rgba(96, 165, 250, 0.3)',
    },
  },
  {
    id: 'nature',
    label: 'Nature',
    vars: {
      '--bg-color': '#f6fbf7',
      '--surface-color': '#ffffff',
      '--surface-muted': '#eef7f0',
      '--text-color': '#163320',
      '--muted-color': '#3f5f4a',
      '--primary-color': '#2f9e44',
      '--secondary-color': '#2f4b39',
      '--accent-color': '#e6f4ea',
      '--border-color': '#9fc7aa',
      '--danger-color': '#dc2626',
      '--danger-contrast-color': '#ffffff',
      '--overlay-color': 'rgba(14, 33, 22, 0.45)',
      '--shadow-color': '14, 33, 22',
      '--skeleton-base': '#dbe7de',
      '--skeleton-highlight': '#edf5ef',
      '--control-bg': '#ffffff',
      '--control-text': '#163320',
      '--control-border': '#7faa90',
      '--control-focus': '#2f9e44',
      '--control-focus-ring': 'rgba(47, 158, 68, 0.22)',
    },
  },
]

export default create(
  persist(
    (set) => ({
      theme: 'light',
      font: 'space-grotesk',
      fontOptions: fontOptions,
      themeOptions: themeOptions,
      setTheme: (theme) => set({ theme }),
      setFont: (font) => set({ font }),
    }),
    {
      name: 'appearance',
      version: 2,
      partialize: (state) => ({ theme: state.theme, font: state.font }),
      migrate: (persistedState) => ({
        theme: persistedState?.theme ?? 'light',
        font: persistedState?.font ?? 'space-grotesk',
      }),
    },
  ),
)
